include:
  - board: 'raytac_mdbt50q_db_40'
    shield: totem_dongle
  - board: 'xiao_ble//zmk'
    shield: totem_left
  - board: 'xiao_ble//zmk'
    shield: totem_right
  - board: 'xiao_ble//zmk'
    shield: settings_reset
  - board: 'raytac_mdbt50q_db_40'
    shield: settings_reset
