include:
  - board: 'raytac_mdbt50q_cx_40_dongle'
    shield: totem_dongle
  - board: 'xiao_ble//zmk'
    shield: totem_left
  - board: 'xiao_ble//zmk'
    shield: totem_right
# there is no settingsreset (needed) for the XIAO
